services:
  nest-upload-api:
    container_name: nestjs-file-upload
    build: .
    ports:
      - "3100:3100"
    volumes:
      - ./uploads:/app/uploads
    networks:
      - app-network
    depends_on:
      - clamav
    restart: unless-stopped

  clamav:
    container_name: clamav
    image: clamav/clamav:latest
    ports:
      - "3310:3310"
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge
